sudo: required

services:
  - docker

language: node_js
node_js:
  - "9"

cache:
  yarn: true
  directories:
    - "node_modules"

before_script:
  - yarn install
  - yarn lint

script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd
  - docker build -f ./arm/Dockerfile -t basbloembergen/rpi-kodi-google-home .
  - rm -rf tmp
  - docker build -f ./x86/Dockerfile -t basbloembergen/kodi-google-home .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker tag basbloembergen/kodi-google-home basbloembergen/kodi-google-home:latest
    docker push basbloembergen/kodi-google-home
    docker tag basbloembergen/rpi-kodi-google-home basbloembergen/rpi-kodi-google-home:latest
    docker push basbloembergen/rpi-kodi-google-home
  fi
